# Generated by Django 5.0.8 on 2024-09-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'پیغام', 'verbose_name_plural': 'پیغام ها'},
        ),
    ]
