# Generated by Django 5.0.8 on 2024-09-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weblog_status', models.BooleanField(default=True, verbose_name='وبلاگ فعال باشد ؟')),
            ],
            options={
                'verbose_name': 'نظیمات سایت',
            },
        ),
    ]
