# Generated by Django 5.0.8 on 2024-09-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reserve_status',
            field=models.BooleanField(default=True, verbose_name='رزرو کردن دستگاه ها فعال باشد ؟'),
        ),
    ]
