# Generated by Django 5.0.8 on 2024-10-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesettings_reserve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='price_pc',
            field=models.IntegerField(default=20000, verbose_name='هزینه کامپیوتر به ازای هر ساعت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_per_controoler_ps4',
            field=models.IntegerField(default=5000, verbose_name='هزینه دسته اضافه ps4 به ازای هر ساعت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_per_controoler_ps5',
            field=models.IntegerField(default=10000, verbose_name='هزینه دسته اصافه ps5 به ازای هر ساعت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_ps4',
            field=models.IntegerField(default=25000, verbose_name='هزینه ps4 به ازای هر ساعت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_ps5',
            field=models.IntegerField(default=35000, verbose_name='هزینه ps5 به ازای هر ساعت'),
        ),
    ]
