# Generated by Django 5.0.8 on 2025-07-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitesettings_price_pc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظیمات سایت'},
        ),
    ]
