# Generated by Django 5.0.8 on 2024-09-16 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pc',
            options={'verbose_name': 'PC', 'verbose_name_plural': 'PCs'},
        ),
        migrations.AlterModelOptions(
            name='ps4',
            options={'verbose_name': 'PS4', 'verbose_name_plural': 'PS4s'},
        ),
        migrations.AlterModelOptions(
            name='ps5',
            options={'verbose_name': 'PS5', 'verbose_name_plural': 'PS5s'},
        ),
        migrations.CreateModel(
            name='PCGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='reservation.pc', verbose_name='دستگاه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PS4Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='reservation.ps4', verbose_name='دستگاه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PS5Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='reservation.ps5', verbose_name='دستگاه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
