# Generated by Django 5.0.8 on 2024-09-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reserve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزرو ها'},
        ),
        migrations.AlterField(
            model_name='reserve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد رزرو'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date_reserve',
            field=models.DateField(verbose_name='تاریخ رزرو'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='time_end',
            field=models.PositiveIntegerField(verbose_name='ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='time_start',
            field=models.PositiveIntegerField(verbose_name='ساعت شروع'),
        ),
    ]
