# Generated by Django 5.0.8 on 2024-10-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reserve_options_alter_reserve_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='count_controller',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد دسته (فقط برای پلی استیشن)'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='customer_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='شناسه مشتری'),
        ),
    ]
