# Generated by Django 5.0.8 on 2025-07-11 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reserve_count_controller_reserve_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='نام دستگاه')),
                ('type', models.CharField(choices=[('ps4', 'PS4'), ('ps5', 'PS5'), ('pc', 'PC')], db_index=True, max_length=4, verbose_name='نوع دستگاه')),
                ('status', models.BooleanField(default=True, verbose_name='آیا دستگاه فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
        ),
        migrations.RemoveField(
            model_name='pcgame',
            name='device',
        ),
        migrations.RemoveField(
            model_name='ps4game',
            name='device',
        ),
        migrations.RemoveField(
            model_name='ps5game',
            name='device',
        ),
        migrations.AlterModelOptions(
            name='reserve',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='object_pk',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='count_controller',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد دسته'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='customer_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='reservation.device', verbose_name='دستگاه'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='نام بازی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='reservation.device', verbose_name='دستگاه')),
            ],
        ),
        migrations.DeleteModel(
            name='PC',
        ),
        migrations.DeleteModel(
            name='PCGame',
        ),
        migrations.DeleteModel(
            name='PS4',
        ),
        migrations.DeleteModel(
            name='PS4Game',
        ),
        migrations.DeleteModel(
            name='PS5',
        ),
        migrations.DeleteModel(
            name='PS5Game',
        ),
    ]
